package com.wutsi.application.store.endpoint

object Page {
    const val CART = "page.cart"
    const val CATALOG = "page.catalog"
    const val CHECKOUT_REVIEW = "page.checkout.review"
    const val CHECKOUT_PIN = "page.checkout.pin"
    const val CHECKOUT_SUCCESS = "page.checkout.success"
    const val CHECKOUT_ERROR = "page.checkout.error"
    const val CHECKOUT_DELIVERY_METHOD = "page.checkout.delivery.method"
    const val CHECKOUT_ADDRESS = "page.checkout.address"
    const val CHECKOUT_ADDRESS_COUNTRY = "page.checkout.address.country"
    const val CHECKOUT_ADDRESS_EDITOR = "page.checkout.address.editor"
    const val ORDERS = "page.orders"
    const val ORDER = "page.order"
    const val PRODUCT = "page.product"
    const val PURCHASES = "page.purchases"
    const val SETTINGS_STORE = "page.settings.store"
    const val SETTINGS_STORE_PRODUCT_LIST = "page.settings.product.list"
    const val SETTINGS_STORE_PRODUCT = "page.settings.store.product"
    const val SETTINGS_STORE_PICTURE = "page.settings.store.picture"
    const val SETTINGS_STORE_PRODUCT_ADD = "page.settings.store.product.add"
    const val SETTINGS_STORE_PRODUCT_EDITOR = "page.settings.store.product.editor"
    const val SETTINGS_STORE_PRODUCT_DESCRIPTION = "page.settings.store.product.description"
    const val SETTINGS_STORE_PRODUCT_FILE = "page.settings.store.product.file"
    const val SETTINGS_STORE_PRODUCT_PRICE = "page.settings.store.product.price"
    const val SETTINGS_STORE_PRODUCT_QUANTIY = "page.settings.store.product.quantity"
    const val SETTINGS_STORE_PRODUCT_MAX_ORDER = "page.settings.store.product.max-order"
    const val SETTINGS_STORE_PRODUCT_COMPARABLE_PRICE = "page.settings.store.product.comparable-price"
    const val SETTINGS_STORE_PRODUCT_SUMMARY = "page.settings.store.product.summary"
    const val SETTINGS_STORE_PRODUCT_SUB_CATEGORY = "page.settings.store.product.sub-category"
    const val SETTINGS_STORE_PRODUCT_TITLE = "page.settings.store.product.title"
    const val SETTINGS_STORE_PRODUCT_TYPE = "page.settings.store.product.type"
    const val SETTINGS_STORE_SHIPPING = "page.settings.store.shipping"
    const val SETTINGS_STORE_SHIPPING_PROFILE = "page.settings.store.shipping.profile"
    const val SETTINGS_STORE_SHIPPING_ATTRIBUTE_DELIVERY_TIME = "page.settings.store.shipping.attribute.delivery-time"
    const val SETTINGS_STORE_SHIPPING_ATTRIBUTE_MESSAGE = "page.settings.store.shipping.attribute.message"
    const val SETTINGS_STORE_SHIPPING_ATTRIBUTE_RATE = "page.settings.store.shipping.attribute.rate"
    const val SETTINGS_STORE_SHIPPING_ATTRIBUTE_CITY = "page.settings.store.shipping.attribute.city"
}
